### ISSUE TITLE
Tereko jeevan mei shanti nhi hai

### ISSUE THREAD

**Issue by himanshu272** [romitkarmakar/covid-19-dashboard#2]

**Comment by romitkarmakar** [comment]
https://www.hackerearth.com/challenges/hackathon/code19-india/
Ismein join kr jaldi se kaal 6 p.m. tk last date hain.

**Comment by himanshu272** [comment]
kar diye hain.
team name

**Comment by romitkarmakar** [comment]
Revolutionary.... Tmko invite send kiye mail mein
